-- Database schema for the scale service website.
-- Run once in the Supabase SQL editor.

create extension if not exists pgcrypto;

create table if not exists public.customers (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  phone text not null default '-',
  job_type text not null check (job_type in ('ขาย', 'ติดตั้ง', 'ซ่อม')),
  job_no text not null unique,
  address text not null default '-',
  province text not null,
  created_year integer not null default extract(year from now())::integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.job_entries (
  id bigint generated by default as identity primary key,
  customer_id uuid not null references public.customers(id) on delete cascade,
  entry_date date not null default current_date,
  description text not null,
  price numeric(12, 2) not null default 0 check (price >= 0),
  bill_no text not null default '-',
  created_at timestamptz not null default now()
);

create index if not exists customers_province_idx on public.customers(province);
create index if not exists customers_created_year_idx on public.customers(created_year desc);
create index if not exists job_entries_customer_id_idx on public.job_entries(customer_id);
create index if not exists job_entries_entry_date_idx on public.job_entries(entry_date desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists customers_set_updated_at on public.customers;
create trigger customers_set_updated_at
before update on public.customers
for each row execute function public.set_updated_at();

alter table public.customers enable row level security;
alter table public.job_entries enable row level security;

drop policy if exists "Authenticated users can read customers" on public.customers;
drop policy if exists "Authenticated users can add customers" on public.customers;
drop policy if exists "Authenticated users can edit customers" on public.customers;
drop policy if exists "Authenticated users can delete customers" on public.customers;

create policy "Authenticated users can read customers"
on public.customers for select to authenticated using (true);
create policy "Authenticated users can add customers"
on public.customers for insert to authenticated with check (true);
create policy "Authenticated users can edit customers"
on public.customers for update to authenticated using (true) with check (true);
create policy "Authenticated users can delete customers"
on public.customers for delete to authenticated using (true);

drop policy if exists "Authenticated users can read entries" on public.job_entries;
drop policy if exists "Authenticated users can add entries" on public.job_entries;
drop policy if exists "Authenticated users can edit entries" on public.job_entries;
drop policy if exists "Authenticated users can delete entries" on public.job_entries;

create policy "Authenticated users can read entries"
on public.job_entries for select to authenticated using (true);
create policy "Authenticated users can add entries"
on public.job_entries for insert to authenticated with check (true);
create policy "Authenticated users can edit entries"
on public.job_entries for update to authenticated using (true) with check (true);
create policy "Authenticated users can delete entries"
on public.job_entries for delete to authenticated using (true);
